# Ditto

[tool.poe.tasks.start-ditto]
help = "Initialize Ditto locally with horizontal scaling"
cwd = "docker"
cmd = "docker compose -f docker-compose.yml up"

[tool.poe.tasks.stop-ditto]
help = "Shutdown local Ditto with horizontal scaling"
cwd = "docker"
cmd = "docker compose -f docker-compose.yml down"

# MQTT broker

[tool.poe.tasks.start-mqtt-broker]
help = "Starts Mosquitto MQTT Broker"
cwd = "examples/config/mosquitto"
sequence = [
    {cmd = "docker pull eclipse-mosquitto:openssl"},
    {cmd = "docker rm -f mosquitto-broker"},
    {cmd = "docker run -d --name mosquitto-broker -p 1883:1883 -p 9001:9001 eclipse-mosquitto:openssl"},
]

[tool.poe.tasks.stop-mqtt-broker]
help = "Stops Mosquitto MQTT Broker"
cmd = "docker rm -f mosquitto-broker"

# Examples

[tool.poe.tasks.e1]
help = "Device State Sync"
cwd = "examples/1-device-state-sync"
cmd = "uv run run.py"

[tool.poe.tasks.e2]
help = "Remote Device Control"
cwd = "examples/2-remote-device-control"
cmd = "uv run run.py"

[tool.poe.tasks.e3]
help = "Digital Twin Enhancement"
cwd = "examples/3-digital-twin-enhancement"
cmd = "uv run run.py"

[tool.poe.tasks.e4]
help = "Outbox Pattern"
cwd = "examples/4-outbox-pattern"
cmd = "uv run run.py"

[tool.poe.tasks.e5]
help = "Inbox Outbox Flow"
cwd = "examples/5-inbox-outbox-flow"
cmd = "uv run run.py"

[tool.poe.tasks.e6]
help = "MQTT Connection"
cwd = "examples/6-mqtt-connection"
cmd = "uv run run.py"

[tool.poe.tasks.e7]
help = "Fleet Management"
cwd = "examples/7-fleet-management"
cmd = "uv run run.py"

# Helpers

[tool.poe.tasks.ruff]
help = "Run all ruff operations: format, check, and fix"
sequence = [
    {cmd = "uv run ruff check . --fix --unsafe-fixes"},
    {cmd = "uv run ruff format ."},  # Format after fixes
    {cmd = "uv run ruff check ."},   # Final check
]

[tool.poe.tasks.cleanup]
help = "Clean up all things, policies, and connections from Ditto"
cmd = "uv run cleanup.py"
