# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.106.0-ferretdb-2.5.0
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    restart: on-failure
    networks:
      ditto_net:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=ditto
      - POSTGRES_PASSWORD=ditto
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.5.0
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    restart: on-failure
    networks:
      ditto_net:
        aliases:
          - ferretdb
    ports:
      - "27017:27017"
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://ditto:ditto@postgres:5432/postgres

  policies:
    image: docker.io/eclipse/ditto-policies:${DITTO_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    restart: always
    networks:
      ditto_net:
        aliases:
          - policies
          - ditto-cluster
    environment:
      - TZ=Europe/Berlin
      - BIND_HOSTNAME=0.0.0.0
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:+UseStringDeduplication -Xss512k -XX:MaxRAMPercentage=65 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=30 -Dpekko.coordinated-shutdown.exit-jvm=on -Dpekko.cluster.shutdown-after-unsuccessful-join-seed-nodes=180s -Dpekko.cluster.failure-detector.threshold=15.0 -Dpekko.cluster.failure-detector.expected-response-after=10s -Dpekko.cluster.failure-detector.acceptable-heartbeat-pause=20s -Dpekko.cluster.downing-provider-class=
      - PEKKO_CLUSTER_SEED_NODES=pekko://ditto-cluster@policies:2552,pekko://ditto-cluster@things:2552,pekko://ditto-cluster@things-search:2552,pekko://ditto-cluster@connectivity:2552
      - LOGGING_LEVEL_org.apache.pekko.cluster.ddata.Replicator=WARN
      - PEKKO_ACTOR_ASK_TIMEOUT=20s
      - PEKKO_HTTP_HOST_CONNECTION_POOL_MAX_OPEN_REQUESTS=128
      - ENABLE_PRE_AUTHENTICATION=true
      - DITTO_THINGS_CLUSTER_SHARDING_ASKTIMEOUT=15s
      - MONGO_DB_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - DITTO_PERSISTENCE_MONGO_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - MONGO_DB_DATABASE=ditto
      - MONGO_DB_SSL_ENABLED=false
    depends_on:
      - postgres
      - ferretdb
    healthcheck:
      test: curl --fail http://localhost:7626/alive || exit 1
      interval: 30s
      timeout: 15s
      retries: 4
      start_period: 120s
    logging:
      options:
        max-size: 50m

  things:
    image: docker.io/eclipse/ditto-things:${DITTO_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    networks:
      ditto_net:
        aliases:
          - things
          - ditto-cluster
    depends_on:
      - policies
    environment:
      - TZ=Europe/Berlin
      - BIND_HOSTNAME=0.0.0.0
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:+UseStringDeduplication -Xss512k -XX:MaxRAMPercentage=65 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=30 -Dpekko.coordinated-shutdown.exit-jvm=on -Dpekko.cluster.shutdown-after-unsuccessful-join-seed-nodes=180s -Dpekko.cluster.failure-detector.threshold=15.0 -Dpekko.cluster.failure-detector.expected-response-after=10s -Dpekko.cluster.failure-detector.acceptable-heartbeat-pause=20s -Dpekko.cluster.downing-provider-class=
      - PEKKO_CLUSTER_SEED_NODES=pekko://ditto-cluster@policies:2552,pekko://ditto-cluster@things:2552,pekko://ditto-cluster@things-search:2552,pekko://ditto-cluster@connectivity:2552
      - LOGGING_LEVEL_org.apache.pekko.cluster.ddata.Replicator=WARN
      - PEKKO_ACTOR_ASK_TIMEOUT=20s
      - PEKKO_HTTP_HOST_CONNECTION_POOL_MAX_OPEN_REQUESTS=128
      - ENABLE_PRE_AUTHENTICATION=true
      - DITTO_THINGS_CLUSTER_SHARDING_ASKTIMEOUT=15s
      - MONGO_DB_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - DITTO_PERSISTENCE_MONGO_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - MONGO_DB_DATABASE=ditto
      - MONGO_DB_SSL_ENABLED=false
    healthcheck:
      test: curl --fail http://localhost:7626/alive || exit 1
      interval: 30s
      timeout: 15s
      retries: 4
      start_period: 120s
    logging:
      options:
        max-size: 50m

  things-search:
    image: docker.io/eclipse/ditto-things-search:${DITTO_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    networks:
      ditto_net:
        aliases:
          - things-search
          - ditto-cluster
    depends_on:
      - policies
    environment:
      - TZ=Europe/Berlin
      - BIND_HOSTNAME=0.0.0.0
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:+UseStringDeduplication -Xss512k -XX:MaxRAMPercentage=65 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=30 -Dpekko.coordinated-shutdown.exit-jvm=on -Dpekko.cluster.shutdown-after-unsuccessful-join-seed-nodes=180s -Dpekko.cluster.failure-detector.threshold=15.0 -Dpekko.cluster.failure-detector.expected-response-after=10s -Dpekko.cluster.failure-detector.acceptable-heartbeat-pause=20s -Dpekko.cluster.downing-provider-class=
      - PEKKO_CLUSTER_SEED_NODES=pekko://ditto-cluster@policies:2552,pekko://ditto-cluster@things:2552,pekko://ditto-cluster@things-search:2552,pekko://ditto-cluster@connectivity:2552
      - LOGGING_LEVEL_org.apache.pekko.cluster.ddata.Replicator=WARN
      - PEKKO_ACTOR_ASK_TIMEOUT=20s
      - PEKKO_HTTP_HOST_CONNECTION_POOL_MAX_OPEN_REQUESTS=128
      - ENABLE_PRE_AUTHENTICATION=true
      - DITTO_THINGS_CLUSTER_SHARDING_ASKTIMEOUT=15s
      - MONGO_DB_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - DITTO_PERSISTENCE_MONGO_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - MONGO_DB_DATABASE=ditto
      - MONGO_DB_SSL_ENABLED=false
    healthcheck:
      test: curl --fail http://localhost:7626/alive || exit 1
      interval: 30s
      timeout: 15s
      retries: 4
      start_period: 120s
    logging:
      options:
        max-size: 50m

  connectivity:
    image: docker.io/eclipse/ditto-connectivity:${DITTO_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    networks:
      ditto_net:
        aliases:
          - connectivity
          - ditto-cluster
    depends_on:
      - policies
    environment:
      - TZ=Europe/Berlin
      - BIND_HOSTNAME=0.0.0.0
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:+UseStringDeduplication -Xss512k -XX:MaxRAMPercentage=65 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=30 -Dpekko.coordinated-shutdown.exit-jvm=on -Dpekko.cluster.shutdown-after-unsuccessful-join-seed-nodes=180s -Dpekko.cluster.failure-detector.threshold=15.0 -Dpekko.cluster.failure-detector.expected-response-after=10s -Dpekko.cluster.failure-detector.acceptable-heartbeat-pause=20s -Dpekko.cluster.downing-provider-class=
      - PEKKO_CLUSTER_SEED_NODES=pekko://ditto-cluster@policies:2552,pekko://ditto-cluster@things:2552,pekko://ditto-cluster@things-search:2552,pekko://ditto-cluster@connectivity:2552
      - LOGGING_LEVEL_org.apache.pekko.cluster.ddata.Replicator=WARN
      - PEKKO_ACTOR_ASK_TIMEOUT=20s
      - PEKKO_HTTP_HOST_CONNECTION_POOL_MAX_OPEN_REQUESTS=128
      - ENABLE_PRE_AUTHENTICATION=true
      - DITTO_THINGS_CLUSTER_SHARDING_ASKTIMEOUT=15s
      - MONGO_DB_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - DITTO_PERSISTENCE_MONGO_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - MONGO_DB_DATABASE=ditto
      - MONGO_DB_SSL_ENABLED=false
    healthcheck:
      test: curl --fail http://localhost:7626/alive || exit 1
      interval: 30s
      timeout: 15s
      retries: 4
      start_period: 120s
    logging:
      options:
        max-size: 50m
        
  gateway:
    image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    networks:
      ditto_net:
        aliases:
          - gateway
          - ditto-cluster
    depends_on:
      - policies
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Berlin
      - BIND_HOSTNAME=0.0.0.0
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:+UseStringDeduplication -Xss512k -XX:MaxRAMPercentage=65 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=30 -Dpekko.coordinated-shutdown.exit-jvm=on -Dpekko.cluster.shutdown-after-unsuccessful-join-seed-nodes=180s -Dpekko.cluster.failure-detector.threshold=15.0 -Dpekko.cluster.failure-detector.expected-response-after=10s -Dpekko.cluster.failure-detector.acceptable-heartbeat-pause=20s -Dpekko.cluster.downing-provider-class=
      - PEKKO_CLUSTER_SEED_NODES=pekko://ditto-cluster@policies:2552,pekko://ditto-cluster@things:2552,pekko://ditto-cluster@things-search:2552,pekko://ditto-cluster@connectivity:2552
      - LOGGING_LEVEL_org.apache.pekko.cluster.ddata.Replicator=WARN
      - PEKKO_ACTOR_ASK_TIMEOUT=20s
      - PEKKO_HTTP_HOST_CONNECTION_POOL_MAX_OPEN_REQUESTS=128
      - ENABLE_PRE_AUTHENTICATION=true
      - DITTO_THINGS_CLUSTER_SHARDING_ASKTIMEOUT=15s
      - MONGO_DB_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - DITTO_PERSISTENCE_MONGO_URI=mongodb://ditto:ditto@ferretdb:27017/ditto?authSource=admin
      - MONGO_DB_DATABASE=ditto
      - MONGO_DB_SSL_ENABLED=false
    healthcheck:
      test: curl --fail http://localhost:7626/alive || exit 1
      interval: 30s
      timeout: 15s
      retries: 4
      start_period: 120s
    logging:
      options:
        max-size: 50m

  ditto-ui:
    image: docker.io/eclipse/ditto-ui:${DITTO_VERSION:-latest}
    deploy:
      resources:
        limits:
          memory: 32m
    restart: always
    networks:
      ditto_net:
        aliases:
          - ditto-ui
    logging:
      options:
        max-size: 10m
        
  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui:v5.9.1
    deploy:
      resources:
        limits:
          memory: 32m
    restart: always
    networks:
      ditto_net:
        aliases:
          - swagger-ui
    volumes:
       - ./openapi:/usr/share/nginx/html/openapi:ro      
       - ./swagger3-index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - QUERY_CONFIG_ENABLED=true
    command: nginx -g 'daemon off;'  
    logging:
      options:
        max-size: 10m
        
  nginx:
    image: docker.io/nginx:1.27-alpine
    deploy:
      resources:
        limits:
          memory: 32m
    restart: always
    networks:
      ditto_net:
        aliases:
          - nginx
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
       - ./nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
       - ./mime.types:/etc/nginx/mime.types:ro
       - ./index.html:/etc/nginx/html/index.html:ro
      #  - ../../documentation/src/main/resources/images:/etc/nginx/html/images:ro
       - ./wot:/etc/nginx/html/wot:ro
    ports:
      - "${DITTO_EXTERNAL_PORT:-8080}:80"
    depends_on:
      - gateway
      - swagger-ui
    logging:
      options:
        max-size: 10m

networks:
  ditto_net:
    driver: bridge
